steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'functions/rss'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - rss-connector
      - --gen2
      - --runtime=python311
      - --region=europe-west3
      - --source=.
      - --entry-point=rss_connector
      - --trigger-http
      #- --allow-unauthenticated
      - --memory=1GiB
      - --timeout=540s
      - --set-secrets=RSS_FIREBASE_KEY=rss-firebase-key:latest
      - --set-env-vars=PROJECT_ID=${_PROJECT_ID},LOG_LEVEL=INFO

options:
  logging: CLOUD_LOGGING_ONLY
