steps:
  - name: 'python:3.11'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '--target', '/workspace']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - orchestrator-service
      - --gen2
      - --runtime=python311
      - --region=europe-west3
      - --source=.
      - --entry-point=orchestrate_pipeline
      - --trigger-http
      - --timeout=600s # Wichtig: Erhöht, da sie auf 3 andere Funktionen wartet
      - --service-account=serviceaccount-1@mail-summerizer-486619.iam.gserviceaccount.com
      - --set-env-vars=MASTODON_URL=https://europe-west3-mail-summerizer-486619.cloudfunctions.net/mastodon_connector,ALERTS_URL=https://europe-west3-mail-summerizer-486619.cloudfunctions.net/alerts-handler,SENDMAIL_URL=https://europe-west3-mail-summerizer-486619.cloudfunctions.net/sendmail_trigger